Version: 1
Description: Test document
NotObsoleteOptions:
    - option1
    - option2
    - addedoption1
SomeOption:
    - retainedoption1
    - addedoption1
    - addedoption2
NewerOptions:
    - newoption1
    - newoption2
    - newoption3

